### PR TITLE
expand order by last to ensure positional references are replaced with qualified columns

### PR DESCRIPTION
**Pull request by ginter**

### CODE REVIEW

**Review by tobymao — APPROVED** [review]

**Comment by tobymao** [comment]
@barakalon should i revert this?

**Comment by barakalon** [comment]
No. Let's chat about it first. I'm not sure what the desired behavior is.

**Comment by barakalon** [comment]
Could be a good case for the new "execute" test mode.

**Comment by barakalon** [comment]
duckdb is happy with it: https://github.com/tobymao/sqlglot/pull/542

**Pull request merged**
