### PR TITLE
SET commands

### PR DESCRIPTION
**Pull request by barakalon**
MySQL SET commands.

This also adds MySQL's session parameters: @@

### CODE REVIEW

**Review by tobymao — APPROVED** [review]

**Comment by mpf82** [comment]
``SET`` used to be parsed as a "command", correct? and as such, you could basically write anything following it.

This PR breaks parsing valid SET statements, e.g.

Postgres: 
```sql
SET application_name TO "app_admin"
SET SESSION application_name TO "app_admin"
SET LOCAL application_name = "app_admin"
``` 
Syntax: 
> SET [ SESSION | LOCAL ] configuration_parameter { TO | = } { value | 'value' | DEFAULT }
> SET [ SESSION | LOCAL ] TIME ZONE { value | 'value' | LOCAL | DEFAULT }

Reference: https://www.postgresql.org/docs/current/sql-set.html

---

Setting multiple values at once in TSQL:

``SET QUOTED_IDENTIFIER, ANSI_NULLS ON``

Reference: https://learn.microsoft.com/en-us/sql/t-sql/statements/set-statements-transact-sql?view=sql-server-ver16#considerations-when-you-use-the-set-statements

**Comment by tobymao** [comment]
can you implement #2 for now?

**Comment by barakalon** [comment]
I'll be out all day today and did this in a rush:
https://github.com/tobymao/sqlglot/pull/676

Feel free to take over/merge.

**Comment by tobymao** [comment]
ok i'll take over thanks!

**Pull request merged**
