### PR TITLE
ErrorLevel.IMMEDIATE

### PR DESCRIPTION
**Pull request by barakalon**
This is a big change, so let's think about it.

This raises a "super error" if error level is RAISE. That's still the default, so users will start getting larger error messages.

Other options:
1. Change RAISE to only raise the first error and log the rest
    - I'm not sure why a user would want this behavior
2. Make IMMEDIATE the default
3. Remove IMMEDIATE and make RAISE raise immediately

### CODE REVIEW

**Comment by tobymao** [comment]
What do you mean by this is a big change? As it is currently, it looks like it doesn't break anything. Are you suggesting that we should consider doing the bigger change which is #2 or #3?

**Comment by barakalon** [comment]
Not a breaking change, just a big change, in the sense that error messaging is a big part of usability.

One potential issue here: error messages are now unbounded:

```
>>> sqlglot.parse_one("((((((")
...
ParseError: Expecting ). Line 1, Col: 6.
  ((((((

Required keyword: 'this' missing for <class 'sqlglot.expressions.Paren'>. Line 1, Col: 6.
  ((((((

Expecting ). Line 1, Col: 6.
  ((((((

Expecting ). Line 1, Col: 6.
  ((((((

Expecting ). Line 1, Col: 6.
  ((((((

Expecting ). Line 1, Col: 6.
  ((((((

Expecting ). Line 1, Col: 6.
  ((((((

```

So maybe, if we go this direction, we cap the number of errors:
```
ParseError: Expecting ). Line 1, Col: 6.
  ((((((

Required keyword: 'this' missing for <class 'sqlglot.expressions.Paren'>. Line 1, Col: 6.
  ((((((

Expecting ). Line 1, Col: 6.
  ((((((

... and 7 more
```

**Comment by tobymao** [comment]
yea the capped errors seems reasonable, what do you think?

**Comment by barakalon** [comment]
Sure.

And I guess we'll start getting issue reports with longer error messages, so we'll get a feel for how useful this is.

**Review by tobymao — APPROVED** [review]

**Pull request merged**
