### PR TITLE
Fix: preserve alias quotes in explode_to_unnest

### PR DESCRIPTION
**Pull request by georgesittas**
Addresses https://github.com/tobymao/sqlglot/issues/2607#issuecomment-1834410405

cc @cpcloud

### CODE REVIEW

**Review by tobymao — APPROVED** [review]

**Review by cpcloud — APPROVED** [review]
Thank you!

**Comment by georgesittas** [comment]
Seems like this did the trick.

Before:
```python
>>> import sqlglot
>>> sqlglot.transpile('with t(c) as (select [1,2,3]) select unnest(t.c) as "c" from t', "duckdb", "snowflake")
['WITH t(c) AS (SELECT [1, 2, 3]) SELECT IFF(pos = pos_2, c, NULL) AS c FROM t, TABLE(FLATTEN(INPUT => ARRAY_GENERATE_RANGE(0, (GREATEST(ARRAY_SIZE(t.c)) - 1) + 1))) AS _u(seq, key, path, index, pos, this) CROSS JOIN TABLE(FLATTEN(INPUT => t.c)) AS _u_2(seq, key, path, pos_2, c, this) WHERE pos = pos_2 OR (pos > (ARRAY_SIZE(t.c) - 1) AND pos_2 = (ARRAY_SIZE(t.c) - 1))']
```

^ Getting `ambiguous column name 'C'` in Snowflake

After:
```python
>>> import sqlglot
>>> sqlglot.transpile('with t(c) as (select [1,2,3]) select unnest(t.c) as "c" from t', "duckdb", "snowflake")
['WITH t(c) AS (SELECT [1, 2, 3]) SELECT IFF(pos = pos_2, "c", NULL) AS "c" FROM t, TABLE(FLATTEN(INPUT => ARRAY_GENERATE_RANGE(0, (GREATEST(ARRAY_SIZE(t.c)) - 1) + 1))) AS _u(seq, key, path, index, pos, this) CROSS JOIN TABLE(FLATTEN(INPUT => t.c)) AS _u_2(seq, key, path, pos_2, "c", this) WHERE pos = pos_2 OR (pos > (ARRAY_SIZE(t.c) - 1) AND pos_2 = (ARRAY_SIZE(t.c) - 1))']
```

^ Same results as in DuckDB

**Comment by georgesittas** [comment]
This particular query seems to run fine in snowflake:
Screenshot 2023-11-30 at 11 27 02 PM

**Comment by cpcloud** [comment]
Indeed, but you didn't add the constraint I mentioned :)

> If t has a column named "value"

**Comment by georgesittas** [comment]
Ah, whoops :)

Let me see.

**Comment by cpcloud** [comment]
image

**Comment by cpcloud** [comment]
Happy to help work out the kinks.

I am nearly done porting the snowflake ibis backend to pure sqlglot and unnest is one of the remaining sets of test failures.

**Pull request merged**
