### PR TITLE
account for differences in regexp_extract translation

### PR DESCRIPTION
**Pull request by nsfinkelstein**
This pull request address issue https://github.com/tobymao/sqlglot/issues/1182, according to the approach described in https://github.com/tobymao/sqlglot/issues/1182#issuecomment-1431861858.

### CODE REVIEW

**Comment by nsfinkelstein** [comment]
@tobymao I'm sorry to say that I cannot identify the issue from the logs. Any pointers as to why the checks are failing would be appreciated.

**Comment by tobymao** [comment]
@nsfinkelstein you need to run the linters

make check

**Comment by tobymao** [comment]
i'll finish this for you, nice work. thanks for the pr

**Comment by nsfinkelstein** [comment]
Thank you

**Pull request merged**
