### PR TITLE
Like

### PR DESCRIPTION
**Pull request by tobymao**
@yuchaofan13

### CODE REVIEW

**Comment by yuchaofan13** [comment]
Thanks for fixing my code- I thought modifying _parse_create() was the only option and didn't realise TokenType.LIKE could have different parsing functions across RANGE_PARSERS, PROPERTY_PARSERS and CONSTRAINT_PARSERS.

Do you have any idea as to why my original code wasn't working?

**Comment by tobymao** [comment]
yea, there were many problems. most of the code you added wasn’t even being called

**Comment by yuchaofan13** [comment]
> yea, there were many problems. most of the code you added wasn’t even being called

yeah parse_one gave the desired output but I guess things weren't working properly under the hood. Do you have any advice/SOP for making code changes like this? I'm gradually developing a better understanding of the overall codebase but still relying a lot on copying similar code or messily modifying existing code.

**Comment by tobymao** [comment]
you need to really understand what is getting called and what's happening. parsers are in general quite complex because they are very recursive, tracing through the stack and seeing how things work internally will give you a better understanding of what's going on.

**Comment by yuchaofan13** [comment]
> you need to really understand what is getting called and what's happening. parsers are in general quite complex because they are very recursive, tracing through the stack and seeing how things work internally will give you a better understanding of what's going on.

Gotcha, thanks for the advice. Which key modules would you recommend first trying to understand?

**Comment by tobymao** [comment]
the parser and generator

**Pull request merged**
