### PR TITLE
Update oracle.py

### PR DESCRIPTION
**Pull request by gfmartins**
I'm in doubt if it should be equal to postgresql... or mysql implementations
https://docs.oracle.com/cd/B12037_01/server.101/b10759/functions184.htm

### CODE REVIEW

**Review by barakalon — COMMENTED** [review]
Can you move this to [dialect.py](https://github.com/tobymao/sqlglot/blob/main/sqlglot/dialects/dialect.py) and have both this and [postgres.py](https://github.com/tobymao/sqlglot/blob/main/sqlglot/dialects/postgres.py) use it?

Also, a [test](https://github.com/tobymao/sqlglot/blob/main/tests/dialects/test_oracle.py) would be nice :)

**Comment by GeorgeSittas** [comment]
Hey @gfmartins, any plans to finish this? Let me know if you need any help.

**Comment by gfmartins** [comment]
I tried. (:

**Review by GeorgeSittas — APPROVED** [review]
Looks good. Can you also add some tests for Oracle? Check out `test_postgres.py` starting from line 178.

**Pull request merged**
