### PR TITLE
Add Title column constraint

### PR DESCRIPTION
**Pull request by treysp**

### CODE REVIEW

**Comment by treysp** [comment]
A title isn't a "constraint" on the column per se, but I went with that naming given how and where it's specified.

Let me know if you'd prefer another approach.

**Review by GeorgeSittas — APPROVED** [review]
LGTM

**Comment by GeorgeSittas** [comment]
FYI: I'm working on a refactor for column constraint parsing, so I'll probably include these additions later on. For now we can merge them.

**Comment by treysp** [comment]
I'm working on a few more column constraints - do you want me to wait until after you're done and add them to the refactored code?

**Comment by tobymao** [comment]
yes, hold off until that refactor is in place

**Comment by GeorgeSittas** [comment]
I'll make a PR soon

**Comment by jjthomas** [comment]
This change seems to break valid create statements, e.g. `sqlglot.parse_one('CREATE TABLE t(title text, blah integer)')`

**Pull request merged**
