### PR TITLE
Feat(tsql): added support for parsing the OPTION clause

### PR DESCRIPTION
**Pull request by nadav-botanica**

### CODE REVIEW

**Comment by georgesittas** [comment]
Hey @nadav-botanica, thanks a lot for this PR - I can tell you've put a lot of effort in making it.

Having said that, this doesn't look like the right approach for supporting `OPTION` in T-SQL. I'll need to dig deeper to understand the nuances, but having to add `option` in all these different AST nodes and overriding core methods such as `_parse_select` etc just to anticipate this clause seems like a smell.

As I said in a recent [issue](https://github.com/tobymao/sqlglot/issues/2988#issuecomment-1951229407), my guess is that `OPTION` needs to be treated as a "query modifier" (using sqlglot's lingo), so you have to touch as few places as possible in the code.

**Comment by nadav-botanica** [comment]
The current parsing implemented in sql doesn't support the OPTION clause, as specified here: https://learn.microsoft.com/en-us/sql/t-sql/queries/option-clause-transact-sql?view=sql-server-ver16
This patch aims to add support

**Comment by georgesittas** [comment]
Can you try to refactor this based on the above suggestions? We can keep iterating in this PR if you want. Feel free to reach out in [Slack](https://tobikodata.com/slack) if you need assistance.

**Comment by nadav-botanica** [comment]
Hi @georgesittas - thanks for your rapid response and elaborate answer!
I had a look at `_parse_query_modifiers`, and while it does look to fit for the case of adding support for `OPTION` in case of `SELECT` clauses, I had some problems helping it work for `DELETE` and `UPDATE` statements.
I would greatly appreciate your input!

**Comment by georgesittas** [comment]
> Hi @georgesittas - thanks for your rapid response and elaborate answer! I had a look at `_parse_query_modifiers`, and while it does look to fit for the case of adding support for `OPTION` in case of `SELECT` clauses, I had some problems helping it work for `DELETE` and `UPDATE` statements. I would greatly appreciate your input!

Hmm, perhaps we could keep the `option` arg in `Delete` and `Update` and factor out the `OPTION` modifier parsing logic into a method so that it can be reused for them?

**Comment by georgesittas** [comment]
Looks like it will need some more work to refactor this PR, so I'm going to close it for now. @nadav-botanica we're probably gonna tackle this one soon too, but in case you've already made progress feel free to open another PR (probably reach out in Slack in that case).

**Pull request closed without merging**
