### PR TITLE
Added ability to parse CREATE TABLE A LIKE B and CREATE TABLE A (LIKE B INCLUDING...)

### PR DESCRIPTION
**Pull request by yuchaofan13**
CREATE TABLE A LIKE B is allowed in MySQL (https://dev.mysql.com/doc/refman/5.7/en/create-table-like.html) whilst CREATE TABLE A (LIKE B) is allowed in PostgreSQL (https://www.postgresql.org/docs/current/sql-createtable.html).

In Postgres you can further specify the type of deep copy you want to make, e.g. whether to include/exclude constraints, compression etc. (EXCLUDE being the default option). The syntax is then like 'CREATE TABLE A (LIKE B INCLUDING CONSTRAINTS INCLUDING COMPRESSION INCLUDING STATISTICS EXCLUDING COMMENTS)'.

### CODE REVIEW

**Comment by tobymao** [comment]
can you add a test?

**Comment by yuchaofan13** [comment]
> can you add a test?

I know that running parse_one() on the above expressions now gives the desired output. However, I tried adding tests to test_postgres and test_mysql and they failed.

I'm unfamiliar with how validate_identity/validate_all work- how exactly does SQLGlot determine the dialect? Is it to do with the generator/transforms (which I'm also unfamiliar with, and haven't made changes to in this PR yet)?

I've seen examples of adding dialect-specific properties such as TRANSIENT and DISTSTYLE but here I've modified the way 'create table' is parsed and I'm not sure how to go about things.

Some guidance would greatly appreciated!

**Comment by tobymao** [comment]
what test did you add and how did they fail?

**Comment by yuchaofan13** [comment]
> what test did you add and how did they fail?

In test_mysql.py: self.validate_identity("CREATE TABLE A LIKE B")
Which led to AssertionError: 'CREATE TABLE A LIKE B' != 'CREATE TABLE A AS A LIKE B'

And in test_postgres.py: self.validate_identity(
            "CREATE TABLE A (LIKE B INCLUDING STATISTICS INCLUDING CONSTRAINTS INCLUDING DEFAULTS EXCLUDING COMMENTS)"
        )
Which led to AssertionError: 'CREATE TABLE A (LIKE B INCLUDING STATISTICS INCLUDING CO[44 chars]NTS)' != 'CREATE TABLE A AS A LIKE B'

**Comment by tobymao** [comment]
seems like your code doesn't work then

**Comment by tobymao** [comment]
closed in favor of #760

**Pull request closed without merging**
