### PR TITLE
Update postgres.py

### PR DESCRIPTION
**Pull request by Kanishkaa07**
Added a support for the TOP keyword in postgres

### CODE REVIEW

**Comment by georgesittas** [comment]
@Kanishkaa07 we're not going to accept a PR unless you communicate what you're trying to do. Please don't spam.

**Comment by Kanishkaa07** [comment]
I'm trying to make the top keyword accept in postgres as postgres won't
accept top keyword instead it uses limit keyword

**Comment by georgesittas** [comment]
Can you provide the relevant documentation that indicates this clause is supported in Postgres? I don't think it is.

**Comment by Kanishkaa07** [comment]
It's not supported in postgres so i altered the code to make it supported
in postgres

**Pull request closed without merging**
