### PR TITLE
Add DialectType for all dialect names

### PR DESCRIPTION
**Pull request by EugeneTorap**
Add DialectType enum for all dialect names

### CODE REVIEW

**Comment by EugeneTorap** [comment]
@tobymao Can you use squash merge?
image

**Review by tobymao — APPROVED** [review]

**Comment by EugeneTorap** [comment]
@tobymao Can you merge and create a new version 4.5.1?

**Comment by tobymao** [comment]
@EugeneTorap are you in a rush? i was gonna fix a couple issues first

**Comment by EugeneTorap** [comment]
Ok, fix them and bump the sqlglot

**Comment by tobymao** [comment]
will do, send me a message on discord

**Comment by barakalon** [comment]
Is “Type” the right suffix? I feel like it’s more… “Name”. But I guess that looks a little stranger.

Also, should the actual Dialect classes get their names from this enum?

**Comment by EugeneTorap** [comment]
@tobymao Can you refactor `DialectType` -> `DialectName` ?

**Comment by EugeneTorap** [comment]
> Also, should the actual Dialect classes get their names from this enum?

I think yes, it's best to use constants rather than literals.

**Comment by tobymao** [comment]
i'll have a new PR to refactor this, thanks for the feedback @barakalon

**Comment by tobymao** [comment]
@barakalon https://github.com/tobymao/sqlglot/pull/328

**Pull request merged**
