### PR TITLE
Make type annotation more robust

### PR DESCRIPTION
**Pull request by GeorgeSittas**

### CODE REVIEW

**Comment by tobymao** [comment]
add a test case, it should no longer crash

**Review by tobymao — APPROVED** [review]

**Comment by GeorgeSittas** [comment]
> add a test case, it should no longer crash

In main, SQLGlot crashes only for the four rules specified in the below example. If we use the complete optimizer pipeline it doesn't crash, so I wasn't sure if we want to test just this subset of rules.

```python
>>> import sqlglot
>>> expr = sqlglot.parse_one("SELECT * FROM (SELECT * FROM bla.foo) WHERE baz <= 0")
>>>
>>> from sqlglot.optimizer.annotate_types import annotate_types
>>> from sqlglot.optimizer.expand_laterals import expand_laterals
>>> from sqlglot.optimizer.qualify_columns import qualify_columns
>>> from sqlglot.optimizer.qualify_tables import qualify_tables
>>>
>>> from sqlglot.optimizer import optimize
>>>
>>> rules = (
...     qualify_tables,
...     qualify_columns,
...     expand_laterals,
...     annotate_types,
... )
>>>
>>> optimize(expr, rules=rules).sql()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/georgesittas/Code/tobiko/sqlglot/sqlglot/optimizer/optimizer.py", line 90, in optimize
    expression = rule(expression, **rule_kwargs)
  File "/Users/georgesittas/Code/tobiko/sqlglot/sqlglot/optimizer/annotate_types.py", line 31, in annotate_types
    return TypeAnnotator(schema, annotators, coerces_to).annotate(expression)
  File "/Users/georgesittas/Code/tobiko/sqlglot/sqlglot/optimizer/annotate_types.py", line 290, in annotate
    col.type = selects[col.table][col.name].type
KeyError: 'baz'
>>>
>>> optimize(expr).sql()
'SELECT * FROM "bla"."foo" AS "foo" WHERE "foo"."baz" <= 0'
```

**Comment by tobymao** [comment]
due to pushdown? if so we should add pushdown as well to sqlmesh

**Comment by GeorgeSittas** [comment]
> due to pushdown?

Probably, yeah.

**Pull request merged**
