### PR TITLE
Chore: Update installation steps in README to include sqlglotrs

### PR DESCRIPTION
**Pull request by izeigerman**

### CODE REVIEW

**Review by tobymao — COMMENTED** [review]
shouldn’t this be an option?

**Comment by izeigerman** [comment]
@tobymao don't we want it to be a default one though?

**Comment by tobymao** [comment]
> @tobymao don't we want it to be a default one though?

ok let’s make it default but say if you want pure python to exclude it

**Comment by izeigerman** [comment]
@tobymao updated, let me know

**Review by tobymao — APPROVED** [review]

**Pull request merged**
