### PR TITLE
Fix(doris): postgres interval type date function 

### PR DESCRIPTION
**Pull request by Toms1999**
**Before you file an issue**
- Make sure you specify the "read" dialect eg. `parse_one(sql, read="postgres")`
- Make sure you specify the "write" dialect eg. `ast.sql(dialect="doris")`
- Check if the issue still exists on main:Couldn't find anything related

**Fully reproducible code snippet**
```python
import sqlglot

sql = """SELECT NOW() - INTERVAL '1 YEAR + 1 MONTH'"""

print(sqlglot.transpile(sql ,read="postgres" , write="doris")[0]);
``` 

output
```
SELECT NOW() - INTERVAL '1 YEAR + 1 MONTH'
```

Expected output
```
SELECT NOW() - INTERVAL '1' YEAR - INTERVAL '1' MONTH

```

```python
import sqlglot

sql = """SELECT NOW() - INTERVAL '1 YEAR - 1 MONTH'"""

print(sqlglot.transpile(sql ,read="postgres" , write="doris")[0]);
``` 

output
```
SELECT NOW() - INTERVAL '1 YEAR - 1 MONTH'
```

Expected output
```
SELECT NOW() - INTERVAL '1' YEAR + INTERVAL '1' MONTH

```

image

### CODE REVIEW

**Comment by georgesittas** [comment]
@Toms1999 please don't spam, I already explained that this is not looking right in the other one. We're not going to accept PRs if you're not going to communicate with us. Also, please avoid opening PRs that don't pass CI checks.

**Comment by Toms1999** [comment]
@georgesittas i am sorry , but Can you elaborate on what the problem is please

**Comment by Toms1999** [comment]
@georgesittas Also sorry I only checked the style, next time I will make sure make test

**Comment by georgesittas** [comment]
> @georgesittas i am sorry , but Can you elaborate on what the problem is please

This is being parsed incorrectly, I shared a similar example in the other PR too:

```python
>>> import sqlglot
>>> sqlglot.transpile("SELECT NOW() + INTERVAL '1 YEAR - 1 MONTH'", "postgres", "doris")
["SELECT NOW() + INTERVAL '1' YEAR + INTERVAL '1' MONTH"]
```

You're converting a `+` into a `Sub`, assuming that there is a `-` operator preceding the `INTERVAL`, which isn't necessarily the case. You need to preserve the operations and wrap the whole thing in parentheses for this transformation to work.

> sorry I only checked the style, next time I will make sure make test

Make sure to commit the style changes made by `make style`, otherwise CI will fail.

**Pull request closed without merging**
