### PR TITLE
Stricter named_selects

### PR DESCRIPTION
**Pull request by barakalon**
fixes https://github.com/tobymao/sqlglot/issues/999

`Expression.alias_or_name` is a bit too lenient in many cases:

```python
parse_one("1 + 2").alias_or_name
# '1'
```

So this introduces yet another concept - "output_name". 
I'm not crazy about adding a new method. But this seems safer than mucking with `Expression.alias_or_name`. Happy to hear opinions here.

@tobymao @GeorgeSittas

### CODE REVIEW

**Comment by barakalon** [comment]
I'm also not sure if the output_name of `CAST(a AS INT)` should be `a`, as it is now.

**Comment by tobymao** [comment]
do we really need to have output_name?

**Comment by barakalon** [comment]
Either that or:
1. We change the default behavior of `Expression.name`
2. We move this logic into the optimizer... but that would introduce even more conflicting concepts.

**Comment by barakalon** [comment]
Or maybe we should need to fix Expression.name for a few expression types, e.g. Binary?

**Comment by GeorgeSittas** [comment]
I think the issue still remains even with these changes, I can repro them in this branch locally. Am I missing something?

**Comment by barakalon** [comment]
@GeorgeSittas notice that CAST now has a "number" alias, so it's correct.

This PR now gives us control here. If we prefer, we can remove "CAST"'s output name.

**Review by tobymao — APPROVED** [review]

**Comment by GeorgeSittas** [comment]
> @GeorgeSittas notice that CAST now has a "number" alias, so it's correct.

Totally missed this, thanks for pointing out.

**Pull request merged**
