### PR TITLE
Fix!: make ObjectIdentifier, IntervalSpan and PseudoType DataTypes

### PR DESCRIPTION
**Pull request by GeorgeSittas**
Fixes the issue mentioned in https://github.com/tobymao/sqlglot/pull/2277#issuecomment-1733901567

### CODE REVIEW

**Review by tobymao — APPROVED** [review]
do these have enums?

**Comment by GeorgeSittas** [comment]
> do these have enums?

What do you mean?

**Comment by tobymao** [comment]
exprission.DataType enums?

**Comment by GeorgeSittas** [comment]
Yep I think they do, if I understand the question correctly:

```python
>>> import sqlglot
>>> dir(sqlglot.parse_one("CREATE TABLE public.propertydata (propertyvalue oid)", "postgres").find(sqlglot.exp.DataType).__class__)
['FLOAT_TYPES', 'INTEGER_TYPES', 'NUMERIC_TYPES', 'TEMPORAL_TYPES', 'TEXT_TYPES', 'Type', ....]
```

**Pull request merged**
