### PR TITLE
Use 1-based numbering when reporting line and column numbers in parsing error messages

### PR DESCRIPTION
**Pull request by izeigerman**
IMHO this seems a little more intuitive for lines and columns (as opposed to absolute position) but am open to discussion :)

### CODE REVIEW

**Comment by izeigerman** [comment]
I'm also open to changing this at the implementation layer and not just in error message.

**Comment by izeigerman** [comment]
Never mind. This is not well-thought-out change.

**Comment by tobymao** [comment]
what was wrong?

**Comment by izeigerman** [comment]
@tobymao First I realized that there are also error messages in the tokenizer which require a similar update. Then I realized that if we report it one way in the error message while in the actual parser/tokenizer state it remains 0-based, it'd be really hard to correlate / debug messages + code.

I'm thinking about changing this behavior in the parser/tokenizer state itself.

What do you think about this suggestion overall?

**Comment by tobymao** [comment]
i don't mind as long as it's consistent

**Comment by izeigerman** [comment]
Ok, got it. Submitted https://github.com/tobymao/sqlglot/pull/27

**Pull request closed without merging**
