### PR TITLE
Fix(doris): add more reserved keywords

### PR DESCRIPTION
**Pull request by Toms1999**

### CODE REVIEW

**Comment by Toms1999** [comment]
fix#3526

**Review by Toms1999 — COMMENTED** [review]
fix git version

**Comment by georgesittas** [comment]
@Toms1999 can you please share some docs on this? From what I can tell most of these are also reserved in MySQL, so we could do:

```python
RESERVED_KEYWORDS = {
    **MySQL.Generator.RESERVED_KEYWORDS,
    ...
}
```

**Comment by Toms1999** [comment]
@georgesittas ,yes, most of them are indeed in mysql, but a small part is unique to doris, that is to say, doris cannot be executed, but mysql can, such as cast and sets, so I had to first take all the keywords of mysql and then add the relevant keywords of doris. In addition, there is no relevant document here and the official does not provide it, which is found by our large number of transfer tests

**Comment by Toms1999** [comment]
@georgesittas So, should we just add it to mysql, or should doris rewrite it?

**Comment by georgesittas** [comment]
Check out https://github.com/tobymao/sqlglot/commit/f25a9cdfdfd68b25d519ce0b670e2393737c502d

**Pull request closed without merging**
