### PR TITLE
Fix!(bigquery): reduce eq and neq to null if either operand is null

### PR DESCRIPTION
**Pull request by GeorgeSittas**
Context: https://github.com/tobymao/sqlglot/pull/2403#issuecomment-1760681507

Screenshot 2023-10-14 at 5 06 03 PM

### CODE REVIEW

**Comment by tobymao** [comment]
don’t we do this for another dialect?

**Comment by GeorgeSittas** [comment]
> don’t we do this for another dialect?

Not sure, couldn't find `eq` overridden elsewhere.

**Comment by tobymao** [comment]
do we want to do this for all dialects? can you checkout the meaning of = null in others? it's usually incorrect, we could do this at parse time as well

**Comment by GeorgeSittas** [comment]
> do we want to do this for all dialects? can you checkout the meaning of = null in others? it's usually incorrect, we could do this at parse time as well

I have documented some of the dialects we support that were easy to test:

> > FWIW select (null = null) is null yields null in postgres, sqlite, mysql, duckdb, spark, trino, snowflake, redshift, clickhouse, tsql (couldn't test teradata, oracle, hive, drill, doris, etc).

So yeah perhaps we can replace `=` with the `IS` operator at parse time, but that'd be a breaking change because it changes the semantics. Not sure if I'm missing any weird edge case.

**Comment by tobymao** [comment]
ok if it’s only bq we can keep it

**Comment by GeorgeSittas** [comment]
Cool I think this is good to go from me then.

**Review by tobymao — APPROVED** [review]

**Pull request merged**
