### PR TITLE
Fix: fill in missing implementation details for replace(None)

### LINKED ISSUE #3165: running simplify multiple times fails
**Fully reproducible code snippet**
Please include a fully reproducible code snippet or the input sql, dialect, and expected output.

```
>>> from sqlglot.optimizer.scope import exp
>>> from sqlglot.optimizer.simplify import simplify                                                                                 
>>> from sqlglot import parse_one
>>> ast=parse_one("SELECT a,c,b from table1 where 1 = 1;")
>>> w = ast.find(exp.Where)
>>> w2 = simplify(w)
>>> w2 = simplify(w)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lib/python3.9/site-packages/sqlglot/optimizer/simplify.py", line 109, in simplify
    expression = while_changing(expression, _simplify)
  File "lib/python3.9/site-packages/sqlglot/helper.py", line 211, in while_changing
    expression = func(expression)
  File "lib/python3.9/site-packages/sqlglot/optimizer/simplify.py", line 106, in _simplify
    expression.replace(node)
  File "lib/python3.9/site-packages/sqlglot/expressions.py", line 624, in replace
    value = parent.args[key]
KeyError: 'where'
>>> 
```

in my code i run simplify multiple times as I reduce some elements of a query. in this case, elements in the where clause.

as you see in the sample code, first time works fine but then the where clause was removed and the code fails. 
This used to work before, so I guess some check that they key exists has been removed.

### PR DESCRIPTION
**Pull request by georgesittas**
Fixes #3165

### CODE REVIEW

**Comment by tobymao** [comment]
i think the root issue though is that the expression's parent is not None

**Comment by tobymao** [comment]
https://github.com/tobymao/sqlglot/commit/eb0a6c31c92d16abe785087271b14f7611ff24bc

**Comment by streamnsight** [comment]
@tobymao @georgesittas 
Hi guys, while I appreciate the quick turnaround on this, it seems like there is another change in behavior here:
Shouldn't the `remove_where_true` function in simplify remove the `WHERE TRUE` clause altogether? 
If the test passes with a result of WHERE TRUE after 2 passes of simplify, something seems off.

**Comment by georgesittas** [comment]
IIRC this should match the old behavior: `WHERE TRUE` was indeed removed from the original AST. Using your example:

```python
>>> from sqlglot.optimizer.simplify import simplify
>>> from sqlglot import parse_one
>>> ast=parse_one("SELECT a,c,b from table1 where 1 = 1;")
>>>
>>> w = ast.find(exp.Where)
>>> w2 = simplify(w)
>>> w2 = simplify(w)
>>>
>>> w2.sql()
'WHERE TRUE'
>>> ast
Select(
  expressions=[
    Column(
      this=Identifier(this=a, quoted=False)),
    Column(
      this=Identifier(this=c, quoted=False)),
    Column(
      this=Identifier(this=b, quoted=False))],
  from=From(
    this=Table(
      this=Identifier(this=table1, quoted=False))))
>>> ast.sql()
'SELECT a, c, b FROM table1'
```

Did you mean something else?

**Pull request merged**
