### PR TITLE
Feat(teradata): add support for the SAMPLE clause

### PR DESCRIPTION
**Pull request by GeorgeSittas**
Motivated by #2161

### CODE REVIEW

**Comment by Ashay4u** [comment]
Pardon my limited understanding here, but where is tablesample_sql from teradata.py called from? I did not reach that function in my copy of the code

**Comment by GeorgeSittas** [comment]
@Ashay4u it's called from the base generator's `sql` method when calling `transpile` on a query that contains the `SAMPLE` clause. What do you mean you didn't reach that function?

**Comment by GeorgeSittas** [comment]
Can you share your example so I can try to reproduce this? What I've tried so far reaches that code.

**Comment by Ashay4u** [comment]
Code below
```
sql="""
SELECT * FROM 
	Employee 
	Sample 0.33, .25, .1;
"""

try:
    new_query = sqlglot.transpile(sql, read='teradata', write='databricks', pretty=True)[0]
    print(new_query)
except sqlglot.errors.ParseError as error:
    print(traceback.format_exc())
    print(error.errors)
```

My code does not stop at tablesample_sql in generator.py too during transpile. Am i missing a change somewhere

**Comment by GeorgeSittas** [comment]
Yeah, it doesn't reach that method because you're transpiling to _databricks_. See related comment: https://github.com/tobymao/sqlglot/issues/2161#issuecomment-1708826633.

**Comment by Ashay4u** [comment]
Thanks for clarifying. Where should I make changes to the code to try and fix this? I will try to get this to some acceptable fix

**Comment by Ashay4u** [comment]
For my use case, its an acceptable loss. Is there an easy fix for it?

**Comment by GeorgeSittas** [comment]
The fix is not trivial, at least if you're not experienced with SQLGlot's codebase. One idea is to override `_parse_table_sample` in Teradata and:

- Call `super()._parse_table_sample`
- If that returns a `TableSample`, you can check the first arg of `expressions` and depending on what kind of number it is you can also set another arg like `percent`, `rows` etc.

**Comment by Ashay4u** [comment]
Thanks. Will give it a try. How do I familiarize myself with the codebase details. Is there documentation I can refer or just debug through the code to understand? Again, thanks a lot for being so prompt and helpful

**Comment by GeorgeSittas** [comment]
Sure thing, glad you want to contribute. You can also join our [slack](https://tobikodata.com/slack)btw  if you want to chat.

> How do I familiarize myself with the codebase details. Is there documentation I can refer or just debug through the code to understand?

Yeah I'd suggest debugging through the code and looking into past issues & their fixes to understand the work flow. I think the above outline should cover your use case, so try to work around that.

**Pull request merged**
