### PR TITLE
Fix Hive WITH CUBE/ROLLUP syntax

### LINKED ISSUE #1055: Hive Dialect for "WITH ROLLUP" error
when parsing hive sql, there is a Parse Error

image
image
AND **the error** is 
image

This SQL case is just copied from the official documentation https://cwiki.apache.org/confluence/display/Hive/Enhanced+Aggregation%2C+Cube%2C+Grouping+and+Rollup

### PR DESCRIPTION
**Pull request by GeorgeSittas**
Fixes #1055

### CODE REVIEW

**Comment by GeorgeSittas** [comment]
An alternative for this one is to add a flag in the base generator to switch between the previous supported syntax and Hive's `WITH CUBE/ROLLUP`, so that we duplicate less code over to `hive.py`. Happy to go either way.

**Comment by GeorgeSittas** [comment]
> does hive support the standard way?

The CUBE/ROLLUP docs didn't have an example, so I would guess not.

**Comment by tobymao** [comment]
can we do a flag on parser and gen?

**Comment by GeorgeSittas** [comment]
Yeah I'll fix it

**Comment by GeorgeSittas** [comment]
@tobymao should we rather add the "WITH CUBE/ROLLUP" logic in the base Parser, Generator without using a flag approach? That way we can capture both syntax forms without having to exclude either with a flag.

**Comment by tobymao** [comment]
yes that's what i was suggesting

**Comment by GeorgeSittas** [comment]
Ok I made the changes. It feels like it can be simplified more, let me know if I missed a cleaner way to implement this.

**Review by tobymao — APPROVED** [review]

**Pull request merged**
